#Automatische installatie van Guacamole 
#Dependencies installeren die nodig zijn voor onze Guacamole te maken
- name: Install guacamole 
  hosts: guacamole
  tasks:
    - name: install dependencies
      apt:
        update_cache: yes
        name: 
          - libcairo2-dev
          - libjpeg-turbo8-dev
          - libpng-dev
          - libtool-bin
          - uuid-dev
          - freerdp2-dev
          - libpango1.0-dev
          - libssh2-1-dev
          - libssl-dev
        state: present
      become: true

#Ophalen van de source code voor guacamole

    - name: Download guacamole-server-1.4.0.tar.gz
      get_url:
        url: https://downloads.apache.org/guacamole/1.4.0/source/guacamole-server-1.4.0.tar.gz
        dest: /home/fvanhaecke/Desktop/
        force_basic_auth: yes
      become: true

#Extracten van de net gedownloade tar.gz file

    - name: Extract guacamole-server-1.4.0.tar.gz
      ansible.builtin.unarchive:
        src: /home/fvanhaecke/Desktop/guacamole-server-1.4.0.tar.gz
        dest: /home/fvanhaecke/Desktop/
        remote_src: yes
      become: true

#Runnen van het configure script.

    - name: run configure script
      ansible.builtin.shell:
        chdir: /home/fvanhaecke/Desktop/guacamole-server-1.4.0
        cmd: ./configure --with-init-dir=/etc/init.d
      become: true  

#uitvoeren van commando "make" om de server te compilen

    - name: make
      ansible.builtin.shell:
        chdir: /home/fvanhaecke/Desktop/guacamole-server-1.4.0
        cmd: make
      become: true  

#uitvoeren van make install

    - name: make install
      ansible.builtin.shell:
        chdir: /home/fvanhaecke/Desktop/guacamole-server-1.4.0
        cmd: make install
      become: true  

#Guacamole Client
#Guacamole client.war file afhalen.

    - name: Download guacamole-1.4.0.war
      get_url:
        url: https://apache.org/dyn/closer.lua/guacamole/1.4.0/binary/guacamole-1.4.0.war?action=download
        dest: /home/fvanhaecke/Desktop/
      become: true

#Installatie van java

    - name: installing java
      apt:
        name: openjdk-17-jdk
        state: present
      become: true

#user toevoegen voor Apache Tomcat.
#even comment maken omdat ik error krijg dat deze al bestaat
    - name: create tomcat user
      ansible.builtin.shell:
        cmd: useradd -m -U -d /opt/tomcat -s /bin/false tomcat
      become: true
  
#Downloaden van Apache Tomcat

    - name: Download Apache Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
        dest: /home/fvanhaecke/Desktop/
      become: true

#Aanmaken van /opt/tomcat Directory

    - name: Create /opt/tomcat directory
      file:
        path: /opt/tomcat
        state: directory
      become: true

#Unzippen van tomcat.tar naar /opt/tomcat

    - name: Extract tomcat - 9.0.65.tar.gz
      ansible.builtin.unarchive:
        src: /home/fvanhaecke/Desktop/apache-tomcat-9.0.65.tar.gz
        dest: /opt/tomcat
        remote_src: yes
      become: true

#hernoemen van /opt/tomcat/apache-tomcat-9.0.65 naar tomcatapp

    - name: rename tomcatapps
      ansible.builtin.shell:
        chdir: /opt/tomcat
        cmd: mv apache-tomcat-9.0.65 tomcatapp
      become: true

#Ownership wijzigen van /opt/tomcat

    - name: change ownership from /opt/tomcat
      ansible.builtin.shell:
        cmd: "chown -R tomcat: /opt/tomcat"
      become: true

#Scripts in /opt/tomcat/tomcatapp uitvoerbaar maken

    - name: make scripts executable
      ansible.builtin.shell:
        cmd: | 
          find /opt/tomcat/tomcatapp/bin/ -type f -iname "*.sh" -exec chmod +x {} \;
      become: true
      

#Tomcat.service file aanmaken met ansible.file

    - name: Touch tomcat.service
      ansible.builtin.file:
        path: /etc/systemd/system/tomcat.service
        state: touch
      become: true

#Nodige informatie in tomcat.service plaatsen

    - name: edit tomcat.service
      blockinfile:
        block: |
         [Unit]
         Description=Tomcat 9 servlet container
         After=network.target

         [Service]
         Type=forking

         User=tomcat
         Group=tomcat

         Environment="JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64"
         Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom -Djava.awt.headless=true"

         Environment="CATALINA_BASE=/opt/tomcat/tomcatapp"
         Environment="CATALINA_HOME=/opt/tomcat/tomcatapp"
         Environment="CATALINA_PID=/opt/tomcat/tomcatapp/temp/tomcat.pid"
         Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

         ExecStart=/opt/tomcat/tomcatapp/bin/startup.sh
         ExecStop=/opt/tomcat/tomcatapp/bin/shutdown.sh

         [Install]
         WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service
      become: true 

#Reloaden van daemons

    - name: daemon-reload
      ansible.builtin.shell:
        cmd: systemctl daemon-reload
      become: true
      
#starten en enablen van tomcat.service

    - name: start tomcat.service
      ansible.builtin.shell:
        cmd: systemctl start tomcat.service
      become: true

    - name: enable tomcat.service
      ansible.builtin.shell:
        cmd: systemctl enable tomcat.service
      become: true

#enable ufw 8080/tcp

    - name: allow ufw
      ansible.builtin.shell:
        cmd: ufw allow 8080/tcp
      become: true

#Aanmaken van /etc/guacamole directory

    - name: Create etc/guacamole
      file:
        path: /etc/guacamole
        state: directory
      become: true

#verplaatsen van guacamole.war naar /etc/guacamole

    - name: move guacamole.war
      ansible.builtin.shell:
        chdir: /home/fvanhaecke/Desktop/
        cmd: mv guacamole-1.4.0.war /etc/guacamole/guacamole.war
      become: true

#Symlink aanmaken van guacamole client naar tomcat webapps directory

    - name: create symlink 
      ansible.builtin.shell:
        chdir: /home/fvanhaecke/Desktop/
        cmd: ln -s /etc/guacamole/guacamole.war /opt/tomcat/tomcatapp/webapps/
      become: true

# Create GUACAMOLE_HOME environment variabel

    - name: create symlink 
      ansible.builtin.shell:
        chdir: /home/fvanhaecke/Desktop/
        cmd: |
         echo "GUACAMOLE_HOME=/etc/guacamole" | sudo tee -a /etc/default/tomcat
         echo "export GUACAMOLE_HOME=/etc/guacamole" | sudo tee -a /etc/profile
      become: true

# Create guacamole config file

    - name: Touch guacamole.properties
      ansible.builtin.file:
        path: /etc/guacamole/guacamole.properties
        state: touch
      become: true

#configuratiefile aanvullen

    - name: edit tomcat.service
      blockinfile:
        block: |
         guacd-hostname: 127.0.0.1
         guacd-port:     4822
         user-mapping:
         /etc/guacamole/user-mapping.xml
         auth-provider:   net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider
        dest: /etc/guacamole/guacamole.properties
      become: true 

#aanmaken van user-mapping.xml

    - name: Touch user-mapping.xml
      ansible.builtin.file:
        path: /etc/guacamole/user-mapping.xml
        state: touch
      become: true

#Nodige informatie schrijven naar user-mapping.xml


    - name: edit tomcat.service
      blockinfile:
        block: |
         <user-mapping>

             <!-- Per-user authentication and config information -->

             <!-- A user using md5 to hash the password
                  guacadmin user and its md5 hashed password below is used to 
                      login to Guacamole Web UI-->
             <!-- FIRST USER -->
             <authorize 
                     username="fvanhaecke"
                     password="68eacb97d86f0c4621fa2b0e17cabd8c"
                     encoding="md5">

                 <!-- First authorized Remote connection -->
                 <connection name="Ubuntu 22.04LTS">
                     <protocol>ssh</protocol>
                     <param name="hostname">203.0.113.2</param>
                     <param name="port">22</param>
                 </connection>


             </authorize>

             <!-- SECOND USER -->
             <authorize 
                     username="Nico"
                     password="68eacb97d86f0c4621fa2b0e17cabd8c"
                     encoding="md5">

                 <!-- First authorized Remote connection -->
                 <connection name="Ubuntu 22.04LTS">
                     <protocol>ssh</protocol>
                     <param name="hostname">203.0.113.2</param>
                     <param name="port">22</param>
                 </connection>

             </authorize>

             <!-- THIRD USER -->
             <authorize 
                     username="Klaas"
                     password="68eacb97d86f0c4621fa2b0e17cabd8c"
                     encoding="md5">

                 <!-- First authorized Remote connection -->
                 <connection name="Ubuntu 22.04LTS">
                     <protocol>ssh</protocol>
                     <param name="hostname">203.0.113.2</param>
                     <param name="port">22</param>
                 </connection>

             </authorize>

             <!-- FOURTH USER -->
             <authorize 
                     username="Yoshua"
                     password="68eacb97d86f0c4621fa2b0e17cabd8c"
                     encoding="md5">

                 <!-- First authorized Remote connection -->
                 <connection name="Ubuntu 22.04LTS">
                     <protocol>ssh</protocol>
                     <param name="hostname">203.0.113.2</param>
                     <param name="port">22</param>
                 </connection>

             </authorize>

             <!-- FIFTH USER -->

             <authorize 
                     username="pieterjan"
                     password="68eacb97d86f0c4621fa2b0e17cabd8c"
                     encoding="md5">


                 </connection>
                 <!-- Second authorized Remote connection -->
                 <connection name="Ubuntu 22.04LTS 2">
                     <protocol>ssh</protocol>
                     <param name="hostname">203.0.113.3</param>
                     <param name="port">22</param>
                 </connection>

             </authorize>
             
             <!-- SIXTH USER -->

             <authorize 
                     username="Karel"
                     password="68eacb97d86f0c4621fa2b0e17cabd8c"
                     encoding="md5">


                 </connection>
                 <!-- Second authorized Remote connection -->
                 <connection name="Ubuntu 22.04LTS 2">
                     <protocol>ssh</protocol>
                     <param name="hostname">203.0.113.3</param>
                     <param name="port">22</param>
                 </connection>

             </authorize>
             
             <!-- SEVENTH USER -->

             <authorize 
                     username="Joeri"
                     password="68eacb97d86f0c4621fa2b0e17cabd8c"
                     encoding="md5">


                 </connection>
                 <!-- Second authorized Remote connection -->
                 <connection name="Ubuntu 22.04LTS 2">
                     <protocol>ssh</protocol>
                     <param name="hostname">203.0.113.3</param>
                     <param name="port">22</param>
                 </connection>

             </authorize>             
             
             <!-- EIGHT USER -->

             <authorize 
                     username="Hans"
                     password="68eacb97d86f0c4621fa2b0e17cabd8c"
                     encoding="md5">


                 </connection>
                 <!-- Second authorized Remote connection -->
                 <connection name="Ubuntu 22.04LTS 2">
                     <protocol>ssh</protocol>
                     <param name="hostname">203.0.113.3</param>
                     <param name="port">22</param>
                 </connection>

             </authorize>

         </user-mapping>
        dest: /etc/guacamole/user-mapping.xml
      become: true 

#LDCONFIG

    - name: ldconfig
      ansible.builtin.shell:
        cmd: ldconfig
      become: true

#restart tomcat & guacd

    - name: restart tomcat & guacd
      ansible.builtin.shell:
        chdir: /home/fvanhaecke/Desktop/
        cmd: systemctl restart tomcat guacd
      become: true
